openapi: "3.0.0"
info:
  version: 1.0.0
  title: Web API Demo for rabbitmq
servers:
- url: http://localhost:8182{basePath}
  description: Local development server
  variables:
    basePath:
      default: "/"
tags:
- name: Test
- name: Healthcheck
- name: Monitoring
- name: Command
- name: pets
paths:
  /ping:
    get:
      tags:
      - Test
      - Healthcheck
      - Monitoring
      summary: This is for test purpose only.
      description: 'Reply pong.'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  echo:
                    type: string
                    description: The pong response
                example:
                  echo: pong
  /hello/{name}:
    post:
      tags:
      - name: Command
      summary: A hello command.
      description: 'Say hello to someone.'
      parameters:
        - name: name
          in: path
          description: The name of the one to say hello to.
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Success
  /custom/{routingkey}:
    post:
      tags:
      - name: Command
      summary: Create a message.
      description: 'Send a message to the exchange using the givent routing key.'
      parameters:
        - name: routingkey
          in: path
          description: The routing key for the message.
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Success
components:
  schemas:
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
